### ISSUE TITLE
Exception when list buckets operation

### ISSUE THREAD

**Issue by orlando-kinesso** [Robothy/local-s3#43]
```
$ aws --endpoint-url http://localhost:14205 s3 ls s3://existing-bucket/

argument of type 'NoneType' is not iterable

$ curl -D- http://localhost:14205/existing-bucket
HTTP/1.1 500 Internal Server Error
content-length: 178
content-type: application/xml
connection: keep-alive

<Error><Code>InternalServerError</Code><Message/><RequestId>d244a0dd-4642-4e93-9a74-f1fe7cef0431</RequestId><ArgumentName/><ArgumentValue/><BucketName/><Key/><VersionId/></Error>
```

```
java.lang.NullPointerException: null
	at com.robothy.s3.rest.handler.ListObjectsController.handle(ListObjectsController.java:65)
	at com.robothy.netty.codec.HttpMessageHandler.channelRead0(HttpMessageHandler.java:46)
	at com.robothy.netty.codec.HttpMessageHandler.channelRead0(HttpMessageHandler.java:19)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:61)
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:370)
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

```
        <dependency>
            <groupId>io.github.robothy</groupId>
            <artifactId>local-s3-rest</artifactId>
            <version>1.6</version>
            <scope>test</scope>
        </dependency>
```

**Comment by Robothy** [comment]
LocalS3 doesn't support list buckets yet. Add this feature to the TODO list.

**Comment by Robothy** [comment]
https://github.com/Robothy/local-s3/pull/45

**Comment by orlando-kinesso** [comment]
thank you!
do you have a release date for next release?

**Comment by Robothy** [comment]
The next release at the early Feb.

**Comment by Robothy** [comment]
his feature is released in the latest version.
