### ISSUE TITLE
Shutdown issue in SpringBoot application

### ISSUE THREAD

**Issue by mnbattaglia** [Robothy/local-s3#72]
I'm using a SpringBoot MVC application and I'm starting the LocalS3 instance in a configuration bean @postConstruct and shutting it down in the @PreDestroy. When stopping the application I'm getting the following error:
```
Exception in thread "Thread-3" java.util.concurrent.RejectedExecutionException: event executor terminated
	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:934)
	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:351)
	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:344)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:836)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute0(SingleThreadEventExecutor.java:827)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:817)
	at io.netty.channel.AbstractChannelHandlerContext.safeExecute(AbstractChannelHandlerContext.java:1165)
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:729)
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:560)
	at io.netty.channel.DefaultChannelPipeline.close(DefaultChannelPipeline.java:957)
	at io.netty.channel.AbstractChannel.close(AbstractChannel.java:244)
	at com.robothy.s3.rest.LocalS3.shutdown(LocalS3.java:139)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
It seems that local s3 gets stopped when spring boot app stops, so I think there is no need to manually call the shutdown in this case.
This is not happening in a WebFlux app

**Comment by mnbattaglia** [comment]
Given the following line in the `start()` method:
`Runtime.getRuntime().addShutdownHook(new Thread(this::shutdown));`
Is there any reason to call the `shutdown()` manually? It seems that it fails if the shutdown was already called by the hook

**Comment by mnbattaglia** [comment]
I think the problem is, if I call `shutdown()` when JVM stops it will run the hook and try to do a `shutdown()` again and that's where it fails. The thing is, I need to do the shutdown before the JVM stops while running the Spring Boot app. Otherwise, the java running process gets stuck. I don't know how we can get this working. Probably by making the shutdown hook optional during locals3 start

**Comment by Robothy** [comment]
> Given the following line in the `start()` method: `Runtime.getRuntime().addShutdownHook(new Thread(this::shutdown));` Is there any reason to call the `shutdown()` manually? It seems that it fails if the shutdown was already called by the hook

We use this hook to handle the stop signal from Docker. If you create several LocalS3 instance during test, then manually shutdown is required. We can check if the Netty channels and event executors are open in the `shutdown()` method to ensure they won't be closed multiple times. I'll add a PR to do that.

**Comment by Robothy** [comment]
This issue has been fixed since version `1.12.1`

**Comment by mnbattaglia** [comment]
Thanks A LOT Luo for the quick fix

**Comment by Robothy** [comment]
Reopen this issue for investigation.

**Comment by Robothy** [comment]
https://github.com/Robothy/local-s3/pull/76
