### ISSUE TITLE
Collect reachability meta data

### ISSUE THREAD

**Issue by anshu-zs** [Robothy/local-s3#89]
Hi,
I am trying to build a native image of an in house framework, but I'm not able to figure out how to add META-INF/native-image. Have you added it manually or using some tool?

Thanks

**Comment by anshu-zs** [comment]
Hi @Robothy thanks for replying, I am able to collect metadata using tracing agent but I'm getting this error while running native image. Have you faced this issue while working on this project?

```
Exception in thread "main" io.github.classgraph.ClassGraphException: Uncaught exception during scan
        at io.github.classgraph.ClassGraph.scan(ClassGraph.java:1637)
        at io.github.classgraph.ClassGraph.scan(ClassGraph.java:1654)
        at io.github.classgraph.ClassGraph.scan(ClassGraph.java:1667)
        at com.zopsmart.rocket.engine.scanner.ClassScanner.scanClasses(ClassScanner.java:42)
        at com.zopsmart.rocket.engine.DependencyEngine.build(DependencyEngine.java:714)
        at com.zopsmart.rocket.engine.EngineManager.buildDependencyStore(EngineManager.java:68)
        at com.zopsmart.rocket.context.ContextManager.initStores(ContextManager.java:67)
        at com.zopsmart.rocket.context.ContextManager.initPrimaryContexts(ContextManager.java:48)
        at com.zopsmart.rocket.context.ContextManager.<init>(ContextManager.java:37)
        at com.zopsmart.rocket.Rocket.initialize(Rocket.java:44)
        at com.zopsmart.rocket.Rocket.run(Rocket.java:99)
        at examples.http.Main.main(Main.java:10)
Caused by: java.lang.IllegalArgumentException: Method "list" could not be invoked
        at nonapi.io.github.classgraph.reflection.ReflectionUtils.invokeMethod(ReflectionUtils.java:230)
        at io.github.classgraph.ModuleReaderProxy.list(ModuleReaderProxy.java:111)
        at io.github.classgraph.ClasspathElementModule.scanPaths(ClasspathElementModule.java:318)
        at io.github.classgraph.Scanner$4.processWorkUnit(Scanner.java:1100)
        at io.github.classgraph.Scanner$4.processWorkUnit(Scanner.java:1094)
        at nonapi.io.github.classgraph.concurrency.WorkQueue.runWorkLoop(WorkQueue.java:246)
        at nonapi.io.github.classgraph.concurrency.WorkQueue.access$000(WorkQueue.java:50)
        at nonapi.io.github.classgraph.concurrency.WorkQueue$1.call(WorkQueue.java:201)
        at nonapi.io.github.classgraph.concurrency.WorkQueue$1.call(WorkQueue.java:198)
        at java.base@11.0.18/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base@11.0.18/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base@11.0.18/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base@11.0.18/java.lang.Thread.run(Thread.java:829)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base@11.0.18/java.lang.reflect.Method.invoke(Method.java:566)
        at nonapi.io.github.classgraph.reflection.StandardReflectionDriver.invokeMethod(StandardReflectionDriver.java:193)
        at nonapi.io.github.classgraph.reflection.ReflectionUtils.invokeMethod(ReflectionUtils.java:227)
        ... 14 more
Caused by: com.oracle.svm.core.jdk.UnsupportedFeatureError: JRT file system is disabled
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:89)
        at java.base@11.0.18/jdk.internal.module.SystemModuleFinders$SystemImage.reader(SystemModuleFinders.java:139)
        at java.base@11.0.18/jdk.internal.module.SystemModuleFinders$ModuleContentSpliterator.<init>(SystemModuleFinders.java:508)
        at java.base@11.0.18/jdk.internal.module.SystemModuleFinders$SystemModuleReader.list(SystemModuleFinders.java:483)
        ... 17 more
```

Thanks
